# Generated by Django 2.2.4 on 2019-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190825_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('km', models.FloatField(blank=True, null=True, verbose_name='Расстояние')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Карта')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('trek', models.FileField(upload_to='app/trek/', verbose_name='Фаил пути')),
                ('fotos', models.ImageField(upload_to='app/fotos/', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name_plural': 'Маршруты',
                'verbose_name': 'Маршрут',
            },
        ),
    ]
