# Generated by Django 2.2.4 on 2019-08-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rs',
            name='fotos',
        ),
    ]
