# Generated by Django 2.2.4 on 2019-08-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_rs_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rs',
            name='trek',
            field=models.FileField(upload_to='app/trek/', verbose_name='Трек'),
        ),
    ]
