# Generated by Django 2.2.4 on 2019-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190826_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tl',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
